# Generated by Django 5.1.7 on 2025-06-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
    ]
