# Generated by Django 5.1.7 on 2025-06-02 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='medicamentos',
        ),
        migrations.AddField(
            model_name='compra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.medicamento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='tienda.pedido')),
            ],
        ),
    ]
