# Generated by Django 5.1.7 on 2025-06-06 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.tienda'),
        ),
    ]
