# Generated by Django 5.1.7 on 2025-06-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pedido_direccion_envio_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('devuelto', 'Devuelto')], default='pendiente', max_length=20),
        ),
    ]
