# Generated by Django 5.1.7 on 2025-06-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_pedido_medicamentos_compra_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='medicamentos',
            new_name='medicamento',
        ),
    ]
