# Generated by Django 5.1.7 on 2025-06-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rename_medicamentos_compra_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
