# Generated by Django 5.1.7 on 2025-06-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='denegada',
            field=models.BooleanField(default=False),
        ),
    ]
