# Generated by Django 5.1.7 on 2025-06-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_cliente_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
