# Generated by Django 5.1.7 on 2025-06-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_cuentabancaria_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='saldo',
        ),
    ]
