# Generated by Django 5.1.7 on 2025-06-04 01:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_cliente_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField()),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('aceptado', models.BooleanField(default=False)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('linea_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.lineapedido')),
            ],
        ),
    ]
