# Generated by Django 5.1.7 on 2025-06-14 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productotercero',
            name='tienda',
        ),
        migrations.AddField(
            model_name='productotercero',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productotercero',
            name='fecha_caducidad',
            field=models.DateField(default=datetime.date(2025, 12, 31)),
            preserve_default=False,
        ),
    ]
