# Generated by Django 5.1.7 on 2025-06-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_productotercero_tienda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productotercero',
            old_name='creador',
            new_name='vendedor',
        ),
    ]
